### ISSUE TITLE
Set up github actions

### ISSUE THREAD

**Issue by jacobbien** [jacobbien/litr-project#27]
Make it so that when a user pushes `create-pkg.Rmd` (and any accompanying files source files), it gets litr-knitted, generating both `create-pkg.html` and `pkg/`.

**Comment by patrickvossler18** [comment]
I've been working on a github action that should be run on the push of a new change to the `create-pkg.Rmd` file. I wanted to run the structure by you and check whether I am missing anything. This version of the workflow adds an additional commit with the re-built `create-pkg.html` and `pkg/` directory.

This workflow is derived from the `render-rmarkdown` workflow from `r-lib`. The first part here specifies that we only want this to be run when there are changes to the `create-pkg.Rmd` file
```
# Workflow derived from https://github.com/r-lib/actions/tree/v2/examples
# Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help
on:
  push:
    paths: ['create-*.Rmd', 'source-files/**']

name: render-litr
```

This second part sets up R and pandoc for knitting the file. The most important change here is that we install `litr` after installing `knitr` and `rmarkdown`. We might not need to install `knitr` and `rmarkdown` first since they are dependencies for `litr`.
```
jobs:
  render-litr:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: r-lib/actions/setup-pandoc@v2

      - uses: r-lib/actions/setup-r@v2

      - uses: r-lib/actions/setup-renv@v2
      
      - name: Install litr and dependencies
        run: |
          Rscript -e 'install.packages(c("knitr", "rmarkdown"))'
          Rscript -e 'remotes::install_github("jacobbien/litr-project@*release", subdir = "litr")'

```

This last part is the meat of the workflow. I've kept in the debugging printing since I still need to test this on a repo. `TOP_LEVEL_RMD` uses `find` to find the `create-pkg.Rmd` file and we allow for different capitalizations of Rmd just to be safe. `RMD_FILENAME` strips the file extension to get `create-pkg` and `PKG_NAME` pulls out `pkg` from `create-pkg`. 

`RMD_PATH` looks for our top level Rmd file in the git changes and then we call `litr::render` on that file.

We then call `litr::render` on the `create-pkg.Rmd` file and commit the new versions of the html output and the package directory.
```
      - name: Render Rmarkdown files and Commit Results
        run: |
          TOP_LEVEL_RMD=($(find . -maxdepth 1 -type f  -regex '.*create-.*\.[Rr][Mm][Dd]' -exec basename {} \;))
          echo "$TOP_LEVEL_RMD"
          RMD_FILENAME=${TOP_LEVEL_RMD/.*/}
          PKG_NAME=$(echo "$RMD_FILENAME" | rev | cut -d- -f1 | rev)
          echo "$PKG_NAME"
          RMD_PATH=($(git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep "$TOP_LEVEL_RMD"))
          echo "$RMD_PATH"
          Rscript -e 'for (f in commandArgs(TRUE)) if (file.exists(f)) litr::render(f)' ${RMD_PATH[*]}
          git config --local user.name "$GITHUB_ACTOR"
          git config --local user.email "$GITHUB_ACTOR@users.noreply.github.com"
          git commit "${RMD_FILENAME}.html" "${PKG_NAME}/"  -m 'Re-build Litr file and package' || echo "No changes to commit"
          git push origin || echo "No changes to commit"

```

This only handles the case of a single `.Rmd` file and we will likely need to create a different workflow for packages that use bookdown.

Next step is to try this out on a minimal example and iron out any syntactical issues that come up.
